apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-backend
spec:
  selector:
    app: {{ include "my-fullstack-app-chart.name" . }}-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.backend.service.port }}
