apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-backend
  labels:
    app: {{ include "my-fullstack-app-chart.name" . }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-fullstack-app-chart.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "my-fullstack-app-chart.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
