apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-frontend
  labels:
    {{- include "my-fullstack-app-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: my-fullstack-app-chart
    component: frontend
