apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-frontend
  labels:
    {{- include "my-fullstack-app-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  selector:
    app: {{ include "my-fullstack-app-chart.fullname" . }}-frontend
