apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-frontend
  labels:
    {{- include "my-fullstack-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-fullstack-app-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my-fullstack-app-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: frontend-config
          configMap:
            name: {{ include "my-fullstack-app-chart.fullname" . }}-frontend-config
