apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-frontend-config
  labels:
    app.kubernetes.io/name: {{ include "my-fullstack-app-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  default.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        proxy_pass http://{{ include "my-fullstack-app-chart.fullname" . }}-backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
    }
