frontend:
  replicaCount: 1
  image:
    repository: oeak/frontend-image
    tag: latest
  service:
    port: 80

backend:
  replicaCount: 1
  image:
    repository: oeak/backend-image
    tag: latest
  service:
    port: 3000
  config:
    greetingMessage: "Hello from Helm!"
  secret:
    dbUser: myuser
    dbName: mydb
    # dbPassword kommt aus values-secret.yaml

ingress:
  enabled: true
  ingressClassName: nginx
  host: my-app.local
  paths:
    frontend: /
    backendApi: /api

database:
  auth:
    username: myuser
    database: mydb
    # password kommt aus values-secret.yaml
  primary:
    persistence:
      enabled: true
      size: 8Gi

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
